# Generated by Django 4.1.5 on 2023-01-21 01:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=45)),
                ('started', models.DateTimeField()),
                ('nr_assignments', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3)])),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=None, max_length=25)),
                ('last_name', models.CharField(default=None, max_length=25)),
                ('email', models.EmailField(default=None, max_length=254, unique=True)),
                ('address', models.CharField(default=None, max_length=55)),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Poly-gender', 'Poly-gender'), ('A-gender', 'A-gender'), ('Non-binary', 'Non-binary'), ('Gender-fluid', 'Gender-fluid'), ('Gender-queer', 'Gender-queer'), ('Bi-gender', 'Bi-gender')], default=None, max_length=35)),
                ('country', models.CharField(default=None, max_length=32)),
                ('birth_date', models.DateTimeField(default=None)),
                ('user_student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=None, max_length=25)),
                ('last_name', models.CharField(default=None, max_length=25)),
                ('email', models.EmailField(default=None, max_length=254, unique=True)),
                ('address', models.CharField(default=None, max_length=55)),
                ('phone', models.CharField(default=None, max_length=12)),
                ('user_teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentsCourseRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='system_app.course')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='system_app.studentprofile')),
            ],
            options={
                'unique_together': {('student_id', 'course_id')},
            },
        ),
        migrations.AddField(
            model_name='course',
            name='student',
            field=models.ManyToManyField(related_name='courses', through='system_app.StudentsCourseRelation', to='system_app.studentprofile'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course', to='system_app.teacherprofile'),
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.FileField(upload_to='', verbose_name='assignment_content')),
                ('subject', models.CharField(max_length=45)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_course', to='system_app.course')),
                ('student', models.ManyToManyField(related_name='assignment_student', to='system_app.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.FloatField(default=0)),
                ('assignment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_student', to='system_app.assignment')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_assignment', to='system_app.studentprofile')),
            ],
            options={
                'unique_together': {('assignment_id', 'student_id')},
            },
        ),
    ]
