# Generated by Django 4.1.5 on 2023-01-22 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='student',
        ),
    ]
