# Generated by Django 4.1.5 on 2023-01-22 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_app', '0002_remove_course_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='student',
            field=models.ManyToManyField(related_name='courses', through='system_app.StudentsCourseRelation', to='system_app.studentprofile'),
        ),
    ]
