# Generated by Django 4.1.5 on 2023-01-24 10:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_app', '0003_course_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='nr_students',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
    ]
