# Generated by Django 4.1.5 on 2023-01-24 14:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_app', '0004_course_nr_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='wait_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), default=[], size=None),
        ),
    ]
